package com.amateur.wanbei.dao.mapper;

import com.amateur.wanbei.dao.entity.WbUserProfile;
import com.amateur.wanbei.dao.entity.WbUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WbUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int countByExample(WbUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int deleteByExample(WbUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int insert(WbUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int insertSelective(WbUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    List<WbUserProfile> selectByExample(WbUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    WbUserProfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") WbUserProfile record, @Param("example") WbUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int updateByExample(@Param("record") WbUserProfile record, @Param("example") WbUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int updateByPrimaryKeySelective(WbUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    int updateByPrimaryKey(WbUserProfile record);
}