package com.amateur.wanbei.dao.mapper;

import com.amateur.wanbei.dao.entity.WbWxUserProfile;
import com.amateur.wanbei.dao.entity.WbWxUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WbWxUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int countByExample(WbWxUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int deleteByExample(WbWxUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int insert(WbWxUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int insertSelective(WbWxUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    List<WbWxUserProfile> selectByExample(WbWxUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    WbWxUserProfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") WbWxUserProfile record, @Param("example") WbWxUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int updateByExample(@Param("record") WbWxUserProfile record, @Param("example") WbWxUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int updateByPrimaryKeySelective(WbWxUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_wx_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    int updateByPrimaryKey(WbWxUserProfile record);
}