package com.amateur.wanbei.dao.mapper;

import com.amateur.wanbei.dao.entity.WxLoanOrder;
import com.amateur.wanbei.dao.entity.WxLoanOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxLoanOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int countByExample(WxLoanOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int deleteByExample(WxLoanOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int insert(WxLoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int insertSelective(WxLoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    List<WxLoanOrder> selectByExample(WxLoanOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    WxLoanOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxLoanOrder record, @Param("example") WxLoanOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int updateByExample(@Param("record") WxLoanOrder record, @Param("example") WxLoanOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int updateByPrimaryKeySelective(WxLoanOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_loan_order
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    int updateByPrimaryKey(WxLoanOrder record);
}