package com.amateur.wanbei.dao.entity;

import java.util.Date;

public class WbOperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.id
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.uid
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.name
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.type
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.content
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_operate_log.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.id
     *
     * @return the value of wb_operate_log.id
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.id
     *
     * @param id the value for wb_operate_log.id
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.uid
     *
     * @return the value of wb_operate_log.uid
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.uid
     *
     * @param uid the value for wb_operate_log.uid
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.name
     *
     * @return the value of wb_operate_log.name
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.name
     *
     * @param name the value for wb_operate_log.name
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.type
     *
     * @return the value of wb_operate_log.type
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.type
     *
     * @param type the value for wb_operate_log.type
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.content
     *
     * @return the value of wb_operate_log.content
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.content
     *
     * @param content the value for wb_operate_log.content
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_operate_log.create_time
     *
     * @return the value of wb_operate_log.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_operate_log.create_time
     *
     * @param createTime the value for wb_operate_log.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}