package com.amateur.wanbei.dao.entity;

import java.util.Date;

public class WbUserBinding {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_binding.id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_binding.open_id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_binding.uid
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_binding.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_binding.update_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_binding.id
     *
     * @return the value of wb_user_binding.id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_binding.id
     *
     * @param id the value for wb_user_binding.id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_binding.open_id
     *
     * @return the value of wb_user_binding.open_id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_binding.open_id
     *
     * @param openId the value for wb_user_binding.open_id
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_binding.uid
     *
     * @return the value of wb_user_binding.uid
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_binding.uid
     *
     * @param uid the value for wb_user_binding.uid
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_binding.create_time
     *
     * @return the value of wb_user_binding.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_binding.create_time
     *
     * @param createTime the value for wb_user_binding.create_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_binding.update_time
     *
     * @return the value of wb_user_binding.update_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_binding.update_time
     *
     * @param updateTime the value for wb_user_binding.update_time
     *
     * @mbggenerated Mon Jun 11 09:52:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}