package com.amateur.wanbei.dao.entity;

import java.util.Date;

public class WbUserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.name
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.mobile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.id_card
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.spare_phone1
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String sparePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.spare_phone2
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String sparePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.front_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String frontPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.back_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String backPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user_profile.hand_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    private String handPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.id
     *
     * @return the value of wb_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.id
     *
     * @param id the value for wb_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.name
     *
     * @return the value of wb_user_profile.name
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.name
     *
     * @param name the value for wb_user_profile.name
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.mobile
     *
     * @return the value of wb_user_profile.mobile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.mobile
     *
     * @param mobile the value for wb_user_profile.mobile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.id_card
     *
     * @return the value of wb_user_profile.id_card
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.id_card
     *
     * @param idCard the value for wb_user_profile.id_card
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.create_time
     *
     * @return the value of wb_user_profile.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.create_time
     *
     * @param createTime the value for wb_user_profile.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.spare_phone1
     *
     * @return the value of wb_user_profile.spare_phone1
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getSparePhone1() {
        return sparePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.spare_phone1
     *
     * @param sparePhone1 the value for wb_user_profile.spare_phone1
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setSparePhone1(String sparePhone1) {
        this.sparePhone1 = sparePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.spare_phone2
     *
     * @return the value of wb_user_profile.spare_phone2
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getSparePhone2() {
        return sparePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.spare_phone2
     *
     * @param sparePhone2 the value for wb_user_profile.spare_phone2
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setSparePhone2(String sparePhone2) {
        this.sparePhone2 = sparePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.front_pic
     *
     * @return the value of wb_user_profile.front_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getFrontPic() {
        return frontPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.front_pic
     *
     * @param frontPic the value for wb_user_profile.front_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setFrontPic(String frontPic) {
        this.frontPic = frontPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.back_pic
     *
     * @return the value of wb_user_profile.back_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getBackPic() {
        return backPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.back_pic
     *
     * @param backPic the value for wb_user_profile.back_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setBackPic(String backPic) {
        this.backPic = backPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user_profile.hand_pic
     *
     * @return the value of wb_user_profile.hand_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getHandPic() {
        return handPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user_profile.hand_pic
     *
     * @param handPic the value for wb_user_profile.hand_pic
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setHandPic(String handPic) {
        this.handPic = handPic;
    }


}