package com.amateur.wanbei.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WbUserProfileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public WbUserProfileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSparePhone1IsNull() {
            addCriterion("spare_phone1 is null");
            return (Criteria) this;
        }

        public Criteria andSparePhone1IsNotNull() {
            addCriterion("spare_phone1 is not null");
            return (Criteria) this;
        }

        public Criteria andSparePhone1EqualTo(String value) {
            addCriterion("spare_phone1 =", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1NotEqualTo(String value) {
            addCriterion("spare_phone1 <>", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1GreaterThan(String value) {
            addCriterion("spare_phone1 >", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1GreaterThanOrEqualTo(String value) {
            addCriterion("spare_phone1 >=", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1LessThan(String value) {
            addCriterion("spare_phone1 <", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1LessThanOrEqualTo(String value) {
            addCriterion("spare_phone1 <=", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1Like(String value) {
            addCriterion("spare_phone1 like", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1NotLike(String value) {
            addCriterion("spare_phone1 not like", value, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1In(List<String> values) {
            addCriterion("spare_phone1 in", values, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1NotIn(List<String> values) {
            addCriterion("spare_phone1 not in", values, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1Between(String value1, String value2) {
            addCriterion("spare_phone1 between", value1, value2, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone1NotBetween(String value1, String value2) {
            addCriterion("spare_phone1 not between", value1, value2, "sparePhone1");
            return (Criteria) this;
        }

        public Criteria andSparePhone2IsNull() {
            addCriterion("spare_phone2 is null");
            return (Criteria) this;
        }

        public Criteria andSparePhone2IsNotNull() {
            addCriterion("spare_phone2 is not null");
            return (Criteria) this;
        }

        public Criteria andSparePhone2EqualTo(String value) {
            addCriterion("spare_phone2 =", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2NotEqualTo(String value) {
            addCriterion("spare_phone2 <>", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2GreaterThan(String value) {
            addCriterion("spare_phone2 >", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2GreaterThanOrEqualTo(String value) {
            addCriterion("spare_phone2 >=", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2LessThan(String value) {
            addCriterion("spare_phone2 <", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2LessThanOrEqualTo(String value) {
            addCriterion("spare_phone2 <=", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2Like(String value) {
            addCriterion("spare_phone2 like", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2NotLike(String value) {
            addCriterion("spare_phone2 not like", value, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2In(List<String> values) {
            addCriterion("spare_phone2 in", values, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2NotIn(List<String> values) {
            addCriterion("spare_phone2 not in", values, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2Between(String value1, String value2) {
            addCriterion("spare_phone2 between", value1, value2, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andSparePhone2NotBetween(String value1, String value2) {
            addCriterion("spare_phone2 not between", value1, value2, "sparePhone2");
            return (Criteria) this;
        }

        public Criteria andFrontPicIsNull() {
            addCriterion("front_pic is null");
            return (Criteria) this;
        }

        public Criteria andFrontPicIsNotNull() {
            addCriterion("front_pic is not null");
            return (Criteria) this;
        }

        public Criteria andFrontPicEqualTo(String value) {
            addCriterion("front_pic =", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicNotEqualTo(String value) {
            addCriterion("front_pic <>", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicGreaterThan(String value) {
            addCriterion("front_pic >", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicGreaterThanOrEqualTo(String value) {
            addCriterion("front_pic >=", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicLessThan(String value) {
            addCriterion("front_pic <", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicLessThanOrEqualTo(String value) {
            addCriterion("front_pic <=", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicLike(String value) {
            addCriterion("front_pic like", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicNotLike(String value) {
            addCriterion("front_pic not like", value, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicIn(List<String> values) {
            addCriterion("front_pic in", values, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicNotIn(List<String> values) {
            addCriterion("front_pic not in", values, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicBetween(String value1, String value2) {
            addCriterion("front_pic between", value1, value2, "frontPic");
            return (Criteria) this;
        }

        public Criteria andFrontPicNotBetween(String value1, String value2) {
            addCriterion("front_pic not between", value1, value2, "frontPic");
            return (Criteria) this;
        }

        public Criteria andBackPicIsNull() {
            addCriterion("back_pic is null");
            return (Criteria) this;
        }

        public Criteria andBackPicIsNotNull() {
            addCriterion("back_pic is not null");
            return (Criteria) this;
        }

        public Criteria andBackPicEqualTo(String value) {
            addCriterion("back_pic =", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicNotEqualTo(String value) {
            addCriterion("back_pic <>", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicGreaterThan(String value) {
            addCriterion("back_pic >", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicGreaterThanOrEqualTo(String value) {
            addCriterion("back_pic >=", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicLessThan(String value) {
            addCriterion("back_pic <", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicLessThanOrEqualTo(String value) {
            addCriterion("back_pic <=", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicLike(String value) {
            addCriterion("back_pic like", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicNotLike(String value) {
            addCriterion("back_pic not like", value, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicIn(List<String> values) {
            addCriterion("back_pic in", values, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicNotIn(List<String> values) {
            addCriterion("back_pic not in", values, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicBetween(String value1, String value2) {
            addCriterion("back_pic between", value1, value2, "backPic");
            return (Criteria) this;
        }

        public Criteria andBackPicNotBetween(String value1, String value2) {
            addCriterion("back_pic not between", value1, value2, "backPic");
            return (Criteria) this;
        }

        public Criteria andHandPicIsNull() {
            addCriterion("hand_pic is null");
            return (Criteria) this;
        }

        public Criteria andHandPicIsNotNull() {
            addCriterion("hand_pic is not null");
            return (Criteria) this;
        }

        public Criteria andHandPicEqualTo(String value) {
            addCriterion("hand_pic =", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicNotEqualTo(String value) {
            addCriterion("hand_pic <>", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicGreaterThan(String value) {
            addCriterion("hand_pic >", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicGreaterThanOrEqualTo(String value) {
            addCriterion("hand_pic >=", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicLessThan(String value) {
            addCriterion("hand_pic <", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicLessThanOrEqualTo(String value) {
            addCriterion("hand_pic <=", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicLike(String value) {
            addCriterion("hand_pic like", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicNotLike(String value) {
            addCriterion("hand_pic not like", value, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicIn(List<String> values) {
            addCriterion("hand_pic in", values, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicNotIn(List<String> values) {
            addCriterion("hand_pic not in", values, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicBetween(String value1, String value2) {
            addCriterion("hand_pic between", value1, value2, "handPic");
            return (Criteria) this;
        }

        public Criteria andHandPicNotBetween(String value1, String value2) {
            addCriterion("hand_pic not between", value1, value2, "handPic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wb_user_profile
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 11 09:51:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wb_user_profile
     *
     * @mbggenerated Mon Jun 11 09:51:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}