package com.amateur.wanbei.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WbWxUserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.open_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Integer subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.nickname
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.sex
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.country
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.province
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.city
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.language
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.head_img_url
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.group_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.remark
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.tag_ids
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String tagIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.gmt_subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Date gmtSubscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.gmt_unsubscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Date gmtUnsubscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.latitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.longitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.loc_precision
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private BigDecimal locPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.gmt_locate
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Date gmtLocate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.note
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.deleted
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.creator
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.gmt_create
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.modifier
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.gmt_modify
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_wx_user_profile.union_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    private String unionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.id
     *
     * @return the value of wb_wx_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.id
     *
     * @param id the value for wb_wx_user_profile.id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.open_id
     *
     * @return the value of wb_wx_user_profile.open_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.open_id
     *
     * @param openId the value for wb_wx_user_profile.open_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.subscribe
     *
     * @return the value of wb_wx_user_profile.subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.subscribe
     *
     * @param subscribe the value for wb_wx_user_profile.subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.nickname
     *
     * @return the value of wb_wx_user_profile.nickname
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.nickname
     *
     * @param nickname the value for wb_wx_user_profile.nickname
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.sex
     *
     * @return the value of wb_wx_user_profile.sex
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.sex
     *
     * @param sex the value for wb_wx_user_profile.sex
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.country
     *
     * @return the value of wb_wx_user_profile.country
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.country
     *
     * @param country the value for wb_wx_user_profile.country
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.province
     *
     * @return the value of wb_wx_user_profile.province
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.province
     *
     * @param province the value for wb_wx_user_profile.province
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.city
     *
     * @return the value of wb_wx_user_profile.city
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.city
     *
     * @param city the value for wb_wx_user_profile.city
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.language
     *
     * @return the value of wb_wx_user_profile.language
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.language
     *
     * @param language the value for wb_wx_user_profile.language
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.head_img_url
     *
     * @return the value of wb_wx_user_profile.head_img_url
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.head_img_url
     *
     * @param headImgUrl the value for wb_wx_user_profile.head_img_url
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.group_id
     *
     * @return the value of wb_wx_user_profile.group_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.group_id
     *
     * @param groupId the value for wb_wx_user_profile.group_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.remark
     *
     * @return the value of wb_wx_user_profile.remark
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.remark
     *
     * @param remark the value for wb_wx_user_profile.remark
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.tag_ids
     *
     * @return the value of wb_wx_user_profile.tag_ids
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.tag_ids
     *
     * @param tagIds the value for wb_wx_user_profile.tag_ids
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.gmt_subscribe
     *
     * @return the value of wb_wx_user_profile.gmt_subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Date getGmtSubscribe() {
        return gmtSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.gmt_subscribe
     *
     * @param gmtSubscribe the value for wb_wx_user_profile.gmt_subscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGmtSubscribe(Date gmtSubscribe) {
        this.gmtSubscribe = gmtSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.gmt_unsubscribe
     *
     * @return the value of wb_wx_user_profile.gmt_unsubscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Date getGmtUnsubscribe() {
        return gmtUnsubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.gmt_unsubscribe
     *
     * @param gmtUnsubscribe the value for wb_wx_user_profile.gmt_unsubscribe
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGmtUnsubscribe(Date gmtUnsubscribe) {
        this.gmtUnsubscribe = gmtUnsubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.latitude
     *
     * @return the value of wb_wx_user_profile.latitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.latitude
     *
     * @param latitude the value for wb_wx_user_profile.latitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.longitude
     *
     * @return the value of wb_wx_user_profile.longitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.longitude
     *
     * @param longitude the value for wb_wx_user_profile.longitude
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.loc_precision
     *
     * @return the value of wb_wx_user_profile.loc_precision
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public BigDecimal getLocPrecision() {
        return locPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.loc_precision
     *
     * @param locPrecision the value for wb_wx_user_profile.loc_precision
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setLocPrecision(BigDecimal locPrecision) {
        this.locPrecision = locPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.gmt_locate
     *
     * @return the value of wb_wx_user_profile.gmt_locate
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Date getGmtLocate() {
        return gmtLocate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.gmt_locate
     *
     * @param gmtLocate the value for wb_wx_user_profile.gmt_locate
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGmtLocate(Date gmtLocate) {
        this.gmtLocate = gmtLocate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.note
     *
     * @return the value of wb_wx_user_profile.note
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.note
     *
     * @param note the value for wb_wx_user_profile.note
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.deleted
     *
     * @return the value of wb_wx_user_profile.deleted
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.deleted
     *
     * @param deleted the value for wb_wx_user_profile.deleted
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.creator
     *
     * @return the value of wb_wx_user_profile.creator
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.creator
     *
     * @param creator the value for wb_wx_user_profile.creator
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.gmt_create
     *
     * @return the value of wb_wx_user_profile.gmt_create
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.gmt_create
     *
     * @param gmtCreate the value for wb_wx_user_profile.gmt_create
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.modifier
     *
     * @return the value of wb_wx_user_profile.modifier
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.modifier
     *
     * @param modifier the value for wb_wx_user_profile.modifier
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.gmt_modify
     *
     * @return the value of wb_wx_user_profile.gmt_modify
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.gmt_modify
     *
     * @param gmtModify the value for wb_wx_user_profile.gmt_modify
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_wx_user_profile.union_id
     *
     * @return the value of wb_wx_user_profile.union_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_wx_user_profile.union_id
     *
     * @param unionId the value for wb_wx_user_profile.union_id
     *
     * @mbggenerated Mon Jun 11 09:51:40 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }
}