package com.amateur.wanbei.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WxLoanOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.id
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.loan_amount
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private BigDecimal loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.borrower_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Integer borrowerUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.lend_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Integer lendUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.lend_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private String lendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.borrower_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private String borrowerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.loan_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Date loanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.repay_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Date repayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.delete
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_loan_order.update_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.id
     *
     * @return the value of wx_loan_order.id
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.id
     *
     * @param id the value for wx_loan_order.id
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.loan_amount
     *
     * @return the value of wx_loan_order.loan_amount
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.loan_amount
     *
     * @param loanAmount the value for wx_loan_order.loan_amount
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.borrower_uid
     *
     * @return the value of wx_loan_order.borrower_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Integer getBorrowerUid() {
        return borrowerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.borrower_uid
     *
     * @param borrowerUid the value for wx_loan_order.borrower_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setBorrowerUid(Integer borrowerUid) {
        this.borrowerUid = borrowerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.lend_uid
     *
     * @return the value of wx_loan_order.lend_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Integer getLendUid() {
        return lendUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.lend_uid
     *
     * @param lendUid the value for wx_loan_order.lend_uid
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setLendUid(Integer lendUid) {
        this.lendUid = lendUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.lend_name
     *
     * @return the value of wx_loan_order.lend_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public String getLendName() {
        return lendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.lend_name
     *
     * @param lendName the value for wx_loan_order.lend_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setLendName(String lendName) {
        this.lendName = lendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.borrower_name
     *
     * @return the value of wx_loan_order.borrower_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public String getBorrowerName() {
        return borrowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.borrower_name
     *
     * @param borrowerName the value for wx_loan_order.borrower_name
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setBorrowerName(String borrowerName) {
        this.borrowerName = borrowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.loan_time
     *
     * @return the value of wx_loan_order.loan_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Date getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.loan_time
     *
     * @param loanTime the value for wx_loan_order.loan_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setLoanTime(Date loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.repay_time
     *
     * @return the value of wx_loan_order.repay_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Date getRepayTime() {
        return repayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.repay_time
     *
     * @param repayTime the value for wx_loan_order.repay_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setRepayTime(Date repayTime) {
        this.repayTime = repayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.delete
     *
     * @return the value of wx_loan_order.delete
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.delete
     *
     * @param delete the value for wx_loan_order.delete
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.create_time
     *
     * @return the value of wx_loan_order.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.create_time
     *
     * @param createTime the value for wx_loan_order.create_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_loan_order.update_time
     *
     * @return the value of wx_loan_order.update_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_loan_order.update_time
     *
     * @param updateTime the value for wx_loan_order.update_time
     *
     * @mbggenerated Mon Jun 11 09:51:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}